#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 23 13:26:16 2017
@author: JL
"""
import os
os.chdir(r"/Users/Greer/Desktop/Lending Club - JL")

##### IMPORT ONE CSV
import numpy as np
import pandas as pd
import seaborn as sns

df = pd.read_csv("LendingClub-AllLoans.csv", low_memory=False)
len(df)

